import Foundation

struct ProductDescriptions {
    static let productDescriptions: [String: String] = [
        // Vegetables
        "Fenchel": "Eine knollenartige Pflanze mit mildem, leicht süßlichem Geschmack.",
        "Grünkohl": "Ein dunkelgrünes Blattgemüse, das reich an Vitaminen und Antioxidantien ist.",
        "Gurke / Salatgurke": "Ein erfrischendes Gemüse mit hohem Wassergehalt, ideal für Salate.",
        "Kartoffeln": "Ein vielseitiges Wurzelgemüse, das gekocht, gebraten oder gebacken werden kann.",
        "Kohlrabi": "Eine knollenartige Pflanze mit mildem, nussigem Geschmack.",
        "Kürbis": "Ein großes, orangefarbenes Gemüse, das oft für Suppen und Desserts verwendet wird.",
        "Lauch/Porree": "Ein mild schmeckendes Gemüse aus der Zwiebel-Familie.",
        "Lauch- / Frühlingszwiebeln": "Zarte, milde Zwiebelart, die oft roh in Salaten verwendet wird.",
        "Mais": "Goldgelbe Körner, die süß und saftig schmecken.",
        "Mangold": "Ein Blattgemüse mit kräftigen, bunten Stielen.",
        "Mairüben": "Kleine, weiße Wurzeln mit leicht süßlichem Geschmack.",
        "Karotten": "Orangene Wurzeln, die reich an Beta-Carotin sind.",
        "Paprika": "Knackige, süße oder scharfe Früchte in verschiedenen Farben.",
        "Pastinaken": "Wurzelgemüse mit süßlichem, nussigem Geschmack.",
        "Radieschen": "Kleine, runde Knollen mit scharfem, pfeffrigem Geschmack.",
        "Rosenkohl": "Kleine grüne Knospen mit leicht bitterem Geschmack.",
        "Rote Bete": "Knollengemüse mit intensivem, erdigen Geschmack.",
        "Rotkohl": "Ein purpurrotes Kraut mit mildem, leicht süßem Geschmack.",
        "Rettich": "Ein längliches, scharfes Wurzelgemüse.",
        "Schalotten": "Kleine Zwiebelart mit mildem, süßlichem Geschmack.",
        "Schwarzwurzeln": "Lange, dunkle Wurzeln mit nussigem Geschmack.",
        "Spargel": "Stangenförmiges Gemüse, das weiß oder grün geerntet wird.",
        "Spinat": "Grüne Blätter, die roh oder gekocht gegessen werden können.",
        "Spitzkohl": "Ein zarter, leicht süßlicher Kohl.",
        "Sellerieknollen": "Knollengemüse mit intensivem Geschmack.",
        "Staudensellerie": "Knackige, grüne Stangen mit frischem Geschmack.",
        "Steckrüben": "Gelbliche Wurzeln mit leicht süßlichem Geschmack.",
        "Tomaten": "Saftige, rote Früchte mit vielseitiger Verwendung.",
        "Topinambur": "Kleine Knollen mit nussigem Geschmack.",
        "Weißkohl": "Ein weißer, knackiger Kohl, der für Krautsalat bekannt ist.",
        "Wirsingkohl": "Ein krauser Kohl mit mildem Geschmack.",
        "Zucchini": "Eine grüne Frucht, die oft wie Gemüse verwendet wird.",
        "Zuckerschoten": "Knackige, süße Hülsen mit zarten Erbsen im Inneren.",
        "Zwiebeln": "Würziges, vielseitiges Gemüse für viele Gerichte.",
        "Apfel": "Knackige, süße oder saure Frucht mit vielen Sorten.",
        
        // Citrus Fruits
        "Mandarinen": "Kleine, süße Zitrusfrüchte mit leicht schälbarer Schale.",
        "Mangos": "Süße, tropische Früchte mit saftigem Fruchtfleisch.",
        "Pampelmusen": "Große Zitrusfrucht mit leicht bitterem Geschmack.",
        "Papayas": "Tropische Frucht mit süßem, orangefarbenem Fruchtfleisch.",
        "Zitronen": "Gelbe Zitrusfrucht mit saurem Geschmack.",
        "Batavia": "Ein knackiger, leicht süßer Blattsalat.",
        
        // Leafy Greens and Herbs
        "Chicorée": "Bitteres Blattgemüse, ideal für Salate.",
        "Eichblattsalat": "Weicher Salat mit nussigem Geschmack.",
        "Eisbergsalat": "Knackiger Salat mit mildem Geschmack.",
        "Endiviensalat": "Blattgemüse mit leicht bitterem Geschmack.",
        "Feldsalat": "Zarter Salat mit mild-nussigem Aroma.",
        "Kopfsalat": "Klassischer Salat mit mildem Geschmack.",
        "Lollo Rosso": "Krauser Salat mit leicht bitterem Geschmack.",
        "Portulak": "Zartes Kraut mit leicht säuerlichem Geschmack.",
        "Radicchio": "Roter Salat mit bitterem Geschmack.",
        "Rucola": "Pikantes Kraut mit scharfem Geschmack.",
        "Bärlauch": "Wild wachsendes Kraut mit Knoblaucharoma.",
        "Basilikum": "Aromatisches Kraut, häufig in der mediterranen Küche.",
        "Beifuß": "Aromatisches Kraut, oft in der Küche verwendet.",
        "Bohnenkraut": "Ein pfeffriges Kraut, das zu Bohnen passt.",
        "Borretsch": "Ein Kraut mit mildem Gurkengeschmack.",
        "Dill": "Kraut mit frischem, leicht süßlichem Geschmack.",
        "Estragon": "Ein aromatisches Kraut mit leicht anisartigem Geschmack.",
        "Kerbel": "Ein Kraut mit mildem, anisähnlichem Geschmack.",
        "Koriander": "Ein Kraut mit intensivem, frischem Aroma.",
        "Kresse": "Ein schnell wachsendes Kraut mit scharfem Geschmack.",
        "Liebstöckl": "Ein Kraut mit intensiver Würze.",
        "Lorbeer": "Aromatische Blätter, die für Suppen und Eintöpfe verwendet werden.",
        "Majoran": "Ein Kraut mit würzigem Geschmack.",
        "Minze": "Erfrischendes Kraut mit intensiver Note.",
        "Oregano": "Würziges Kraut, ideal für mediterrane Gerichte.",
        "Petersilie": "Ein vielseitiges Kraut mit frischem Geschmack.",
        "Rosmarin": "Aromatisches Kraut mit harzigem Duft.",
        "Salbei": "Ein Kraut mit intensivem, erdigem Geschmack.",
        "Schnittlauch": "Ein mildes Kraut mit Zwiebelgeschmack.",
        "Thymian": "Ein intensives Kraut mit leicht zitroniger Note.",
        "Zitronenmelisse": "Ein zitroniges Kraut mit mildem Geschmack.",
        
        // Other Vegetables and Fruits
        "Auberginen": "Ein glänzendes, violettes Gemüse mit mildem Geschmack.",
        "Artischocken": "Große, essbare Blütenknospen mit zartem Geschmack.",
        "Blumenkohl": "Ein weißer Kohlkopf mit mildem, leicht nussigem Geschmack.",
        "Bohnen, grüne": "Knackige grüne Hülsenfrüchte mit mildem Geschmack.",
        "Bohnen, dicke": "Fleischige Hülsenfrüchte mit süßlichem Aroma.",
        "Brokkoli": "Grüne Röschen mit mildem Geschmack und vielen Nährstoffen.",
        "Butterrüben": "Ein Wurzelgemüse mit süßem, mildem Aroma.",
        "Champignons": "Pilze mit mildem, erdigem Geschmack.",
        "Chinakohl": "Ein knackiger, milder Kohl.",
        "Erbsen": "Kleine, grüne Hülsenfrüchte mit süßlichem Geschmack.",

        // Fruits
        "Aprikose": "Kleine, saftige Steinfrucht mit samtiger Haut und süß-säuerlichem Geschmack.",
        "Birne": "Süße, saftige Frucht mit weicher Textur, die roh oder gekocht genossen wird.",
        "Blaubeeren / Heidelbeeren": "Kleine, runde Beeren mit süßem Geschmack und hohem Gehalt an Antioxidantien.",
        "Brombeeren": "Schwarze, süß-saure Beeren, ideal für Desserts und Marmeladen.",
        "Erdbeeren": "Leuchtend rote Beeren mit süßem, fruchtigem Geschmack.",
        "Esskastanien": "Nuss mit süßlichem, leicht mehligen Inneren, ideal zum Rösten.",
        "Himbeeren": "Rote Beeren mit intensivem, süßem Aroma und weicher Textur.",
        "Haselnüsse": "Kleine, runde Nüsse mit nussigem, süßlichem Geschmack.",
        "Holunderbeeren / Flieder": "Kleine, schwarze Beeren mit leicht säuerlichem Geschmack.",
        "Johannisbeeren": "Kleine, saure oder süße Beeren, die rot, schwarz oder weiß sein können.",
        "Kirschen": "Runde Steinfrüchte, die süß oder sauer sein können.",
        "Mirabellen": "Kleine, gelbe Pflaumenart mit süßem Geschmack.",
        "Pflaumen": "Steinfrüchte mit saftigem, süßem bis leicht säuerlichem Geschmack.",
        "Preiselbeeren": "Kleine, rote Beeren mit herber, säuerlicher Note.",
        "Quitten": "Gelbe Früchte mit festem, aromatischem Fruchtfleisch, oft für Gelees verwendet.",
        "Pfirsiche": "Saftige Steinfrüchte mit weicher, samtiger Haut und süßem Geschmack.",
        "Nektarinen": "Glattschalige Variante des Pfirsichs mit saftigem, süßem Fruchtfleisch.",
        "Rhabarber": "Stängelpflanze mit saurem Geschmack, oft in Desserts verwendet.",
        "Stachelbeeren": "Grüne, gelbe oder rote Beeren mit leicht säuerlichem Geschmack.",
        "Walnüsse": "Harte Schale mit mild-nussigem, cremigem Kern.",
        "Wassermelonen": "Große Früchte mit süßem, saftigem, rotem Fruchtfleisch.",
        "Weintrauben": "Saftige Früchte, die süß oder säuerlich schmecken, ideal zum Naschen.",
        "Tafeltrauben": "Speziell für den Frischverzehr gezüchtete süße Trauben.",
        "Zwetschgen": "Kleine, ovale Pflaumenart mit festem Fruchtfleisch und süßem Geschmack.",
        "Ananas": "Tropische Frucht mit süß-säuerlichem, saftigem Fruchtfleisch.",
        "Orangen": "Klassische Zitrusfrüchte mit süß-säuerlichem Geschmack.",
        "Avocados": "Cremige, grüne Frucht mit mildem, buttrigem Geschmack.",
        "Bananen": "Lange, süße Früchte mit weichem Fruchtfleisch, ideal als Snack.",
        "Feigen": "Süße, weiche Früchte mit vielen kleinen Samen.",
        "Granatäpfel": "Rote Frucht mit saftigen, süß-säuerlichen Kernen.",
        "Grapefruit": "Große Zitrusfrucht mit bitter-säuerlichem Geschmack.",
        "Kakis": "Süße, orangefarbene Früchte mit weicher, glatter Haut.",
        "Kiwis": "Braune, pelzige Frucht mit grünem, saftigem Inneren und süßem Geschmack.",
        "Limetten": "Kleine grüne Zitrusfrüchte mit intensiv saurem Geschmack.",
        "Litschis": "Tropische Frucht mit süßem, saftigem Inneren und harter Schale."
    ]

    // Funktion zur Beschreibung eines Produkts
    static func description(forProduct productName: String) -> String {
        return productDescriptions[productName] ?? "Beschreibung nicht verfügbar."
    }
}
